---
name: Daily Python Logger

on:
  push:                   # on push
  schedule:
    - cron: "0 8 * * *"   # [minute | hour | day-of-month | month | day-of-week]
  workflow_dispatch:      # manual trigger button

jobs:
  run-daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Install fortune and cowsay
        run: |
          sudo apt-get update
          sudo apt-get install -y fortune cowsay

      - name: Tell a joke
        run: |
          fortune | cowsay >> ./output/joke.txt

      - name: Upload joke
        uses: actions/upload-artifact@v5
        with:
          name: joke
          path: ./output/joke.txt

      - name: Commit output file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./output/joke.txt
          git commit -m "Daily updated joke" || exit 0
          git push
